# This workflow deploys a staging preview to the STAGING Firebase project on every PR.
name: Deploy to Firebase Hosting on PR (Staging)
'on': pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create .env.staging file from individual secrets
        env:
          STAGING_API_KEY: ${{ secrets.STAGING_VITE_API_KEY }}
          STAGING_AUTH_DOMAIN: ${{ secrets.STAGING_VITE_AUTH_DOMAIN }}
          STAGING_PROJECT_ID: ${{ secrets.STAGING_VITE_PROJECT_ID }}
          STAGING_STORAGE_BUCKET: ${{ secrets.STAGING_VITE_STORAGE_BUCKET }}
          STAGING_MESSAGING_SENDER_ID: ${{ secrets.STAGING_VITE_MESSAGING_SENDER_ID }}
          STAGING_APP_ID: ${{ secrets.STAGING_VITE_APP_ID }}
        run: |
          echo "VITE_API_KEY=${STAGING_API_KEY}" > .env.staging
          echo "VITE_AUTH_DOMAIN=${STAGING_AUTH_DOMAIN}" >> .env.staging
          echo "VITE_PROJECT_ID=${STAGING_PROJECT_ID}" >> .env.staging
          echo "VITE_STORAGE_BUCKET=${STAGING_STORAGE_BUCKET}" >> .env.staging
          echo "VITE_MESSAGING_SENDER_ID=${STAGING_MESSAGING_SENDER_ID}" >> .env.staging
          echo "VITE_APP_ID=${STAGING_APP_ID}" >> .env.staging

      - name: Build Staging App
        run: npm ci && npm run build -- --mode staging

      - name: Deploy to Staging Preview Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STAGING }}'
          projectId: rocket-productivity-staging
          channelId: pr-${{ github.event.number }}



