# This workflow deploys a staging preview to the STAGING Firebase project on every PR.
name: Deploy to Firebase Hosting on PR (Staging)
'on': pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create .env.staging file from single secret
        run: |
          echo "VITE_FIREBASE_CONFIG='${{ secrets.VITE_FIREBASE_CONFIG }}'" > .env.staging
      
      - name: DEBUG - Verify .env file has content
        run: |
          echo "Verifying that .env.staging file was created..."
          test -s .env.staging || (echo "ERROR: .env.staging file is empty or was not created." && exit 1)
          echo "File created successfully."

      - name: Build Staging App
        run: npm ci && npm run build -- --mode staging

      - name: Deploy to Staging Preview Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STAGING }}'
          projectId: rocket-productivity-staging
          channelId: pr-${{ github.event.number }}



